name: Build
on:
  push:
    branches: [ 'master' ]

jobs:
  update_mirrors:
    name: Push to mirror repos
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.repository == 'Automattic/temp-test-mirror-source'

    # Not setting a job-level timeout because it would be kind of pointless with the blocking step. Set a step timeout for all other steps instead.
    steps:
      -name: Copy file
       run: cp .nvmrc ./packages/Automattic/temp-test-mirror-source

      - name: Push changed projects
        uses: Automattic/action-push-to-mirrors@v1
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          username: matticbot
          working-directory: ./packages
        timeout-minutes: 5  # 2021-01-18: Successful runs seem to take about half a minute.